### ISSUE TITLE
SPA_MP_Lower_Swivel.stl is not in binary format

### ISSUE THREAD

**Issue by scruss** [makersmakingchange/Sip-And-Puff-Analog-Switch#3]
Clicking on the **[Download](https://github.com/makersmakingchange/Sip-And-Puff-Analog-Switch/raw/master/Build_Files/3D_Printing/SPA_MP_Lower_Swivel.stl)** button at [Sip-And-Puff-Analog-Switch/Build_Files/3D_Printing/SPA_MP_Lower_Swivel.stl](https://github.com/makersmakingchange/Sip-And-Puff-Analog-Switch/blob/master/Build_Files/3D_Printing/SPA_MP_Lower_Swivel.stl) results in a file looking like this being displayed:

    solid OpenSCAD_Model
      facet normal -0.945902 0.307342 -0.103974
        outer loop
          vertex -16.8483 7.27874 -2.20791
          vertex -17.9935 3.82463 -2
          vertex -16.8697 7.28329 -2
        endloop
      endfacet
      facet normal -0.945903 0.307343 -0.103957
        outer loop

While this may be a valid text-format STL that can be saved from the browser, a direct binary download would be consistent with the rest of the project's 3d model files.

**Comment by jakemcivor** [comment]
Thanks - updated a binary version.
